### ISSUE TITLE
the results of chinese or japanese are garbled

### ISSUE THREAD

**Issue by edentsai** [sigito/Linguee-Workflow-for-Alfred#35]
thanks for this awesome workflow.

I tried to translate english to chinese or japanse,
but the results are displayed in grabled,

it maybe an encoding issue.

for example:

- 	destination_language: japanese
  	![destination_language: japanese](https://user-images.githubusercontent.com/5071526/127718418-1b635428-12b2-4abf-b334-c6d85290d9e2.png)

- 	destination_language: chinese
	![destination_language: chinese](https://user-images.githubusercontent.com/5071526/127718526-f37c08d1-0927-4a88-9563-2890a21cc27a.png)

**Comment by sigito** [comment]
Hi @edentsai, thanks for reporting. Definitely, this is an encoding issue. I always decode the HTML data using [the `latin1` encoding](https://github.com/sigito/Linguee-Workflow-for-Alfred/blob/master/Sources/Linguee/Linguee.swift#L24), but for non-latin languages it is actually encoded in `utf8`.

**Comment by sigito** [comment]
Fixed in 1.2.1.

**Comment by edentsai** [comment]
thank you @sigito 👍
