### ISSUE TITLE
Can you add the translation function?

### ISSUE THREAD

**Issue by i110077** [sigito/Linguee-Workflow-for-Alfred#39]
Will this deepl api fail? Do we need to set the api ourselves? Also it would be perfect if the key could add a "Translate" function! Really like this app, thanks again!

**Comment by sigito** [comment]
Hi @i110077, unfortunately this workflow only supports Linguee. And if I understand correctly, you would like to have a workflow that uses Deepl to translate text, right? If so, I do not intend to work on a Deepl workflow at the moment, sorry. I am sure there are already good existing workflows for Deepl you could use.
