### ISSUE TITLE
Does not compile on Sonoma 14.0

### ISSUE THREAD

**Issue by zap2zero** [sigito/Linguee-Workflow-for-Alfred#46]
When I try to compile it on my Sonoma 14.0 MacBook Pro M2, the swift compiler crashes.

Workaround:
When I set `DEBUG` to 1 in the `Makefile`, it works and I can get the workflow to work.

**Comment by sigito** [comment]
Hi, @zap2zero. Thanks for the report. Could you include a build log with an error?
Unfortunately, I haven't yet upgraded to Sonoma, so it might take a little before I address this.

**Comment by zap2zero** [comment]
When compiling with `DEBUG ?= 0` I get the attached log.

It seems to me that swift is just crashing during the process.

[build-log.txt](https://github.com/sigito/Linguee-Workflow-for-Alfred/files/12775452/build-log.txt)

**Comment by sigito** [comment]
It seems to be specific to the fact that the executable target is separate from the actual workflow target. Looks like if I remove the extra executable target, the issue disappears. In the past, the tests wouldn't build for the executable target, but afaict this problem is not present anymore.
